import {
  ArrowRight,
  ArrowLeft,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Copy,
  CreditCard,
  Eye,
  EyeOff,
  File,
  FileText,
  Heart,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Lock,
  Mail,
  Menu,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  Palette,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  Trash,
  User,
  Users,
  X,
  Plus,
  Minus,
  Download,
  Upload,
  ExternalLink,
  Calendar,
  Clock,
  MapPin,
  Phone,
  Globe,
  Zap,
  Camera,
  Video,
  Mic,
  MicOff,
  Volume2,
  VolumeX,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Edit,
  Save,
  Share,
  Filter,
  SortAsc,
  SortDesc,
  Grid,
  List,
  BarChart3,
  PieChart,
  TrendingUp,
  TrendingDown,
  AlertCircle,
  AlertTriangle,
  Info,
  CheckCircle,
  XCircle,
  Gem,
  ShoppingCart,
  Gift,
  Home,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  RefreshCw,
  MessageSquare,
  Share2,
  Grid3x3,
  Truck,
  type LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  // Navigation
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  menu: Menu,
  externalLink: ExternalLink,

  // Actions
  check: Check,
  copy: Copy,
  eye: Eye,
  eyeOff: EyeOff,
  trash: Trash,
  edit: Edit,
  save: Save,
  share: Share,
  download: Download,
  upload: Upload,
  plus: Plus,
  minus: Minus,
  x: X,

  // UI Elements
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  search: Search,
  filter: Filter,
  sortAsc: SortAsc,
  sortDesc: SortDesc,
  grid: Grid,
  grid3x3: Grid3x3,
  list: List,

  // Theme
  sun: Sun,
  moon: Moon,
  laptop: Laptop,

  // User & Account
  user: User,
  users: Users,
  settings: Settings,
  shield: Shield,
  shieldCheck: ShieldCheck,
  lock: Lock,

  // Content
  file: File,
  fileText: FileText,
  image: Image,
  camera: Camera,
  video: Video,
  palette: Palette,

  // Communication
  mail: Mail,
  phone: Phone,
  mic: Mic,
  micOff: MicOff,

  // Audio/Video
  volume2: Volume2,
  volumeX: VolumeX,
  play: Play,
  pause: Pause,
  skipBack: SkipBack,
  skipForward: SkipForward,
  repeat: Repeat,
  shuffle: Shuffle,

  // Location & Time
  mapPin: MapPin,
  calendar: Calendar,
  clock: Clock,
  globe: Globe,

  // Status & Feedback
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  info: Info,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  helpCircle: HelpCircle,

  // Business
  creditCard: CreditCard,
  package: Package,
  barChart3: BarChart3,
  pieChart: PieChart,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,

  // Special - GemsAI specific
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  zap: Zap,
  gem: Gem,
  shoppingCart: ShoppingCart,
  gift: Gift,
  home: Home,
  truck: Truck,

  // Sketch Viewer specific
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  rotateCcw: RotateCcw,
  refreshCw: RefreshCw,
  messageSquare: MessageSquare,
  share2: Share2,

  // Loading
  loader2: Loader2,
  spinner: Loader2, // Alias for compatibility
} as const;

export type IconName = keyof typeof Icons;
